// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuL7ixH0wjzl0C8Sy3QHDmO68i0cNEjN0',
    appId: '1:688758778888:web:3315a3961d9955c37d75bd',
    messagingSenderId: '688758778888',
    projectId: 'wargaplus-a5153',
    authDomain: 'wargaplus-a5153.firebaseapp.com',
    storageBucket: 'wargaplus-a5153.firebasestorage.app',
    measurementId: 'G-N50W1Y9760',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuL7ixH0wjzl0C8Sy3QHDmO68i0cNEjN0',
    appId: '1:688758778888:web:b0a9da569f12d3367d75bd',
    messagingSenderId: '688758778888',
    projectId: 'wargaplus-a5153',
    authDomain: 'wargaplus-a5153.firebaseapp.com',
    storageBucket: 'wargaplus-a5153.firebasestorage.app',
    measurementId: 'G-MT2THK7DM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyam4nZzZTBLf-oEPC2PjwyGOa7oPcLfM',
    appId: '1:688758778888:android:28bf5d61b31f24087d75bd',
    messagingSenderId: '688758778888',
    projectId: 'wargaplus-a5153',
    storageBucket: 'wargaplus-a5153.firebasestorage.app',
  );

}